//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraftLogs.Values {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CraftLogs.Values.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saját magadat / a házadból más csapatokat nem támadhatod meg!.
        /// </summary>
        public static string Arena_CantFight {
            get {
                return ResourceManager.GetString("Arena_CantFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csapat adatai.
        /// </summary>
        public static string Arena_Details {
            get {
                return ResourceManager.GetString("Arena_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A csapat adatai sikeresen beolvasva!.
        /// </summary>
        public static string Arena_Scanned {
            get {
                return ResourceManager.GetString("Arena_Scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aréna.
        /// </summary>
        public static string Arena_Title {
            get {
                return ResourceManager.GetString("Arena_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégse.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CraftLogs.
        /// </summary>
        public static string CraftLogs {
            get {
                return ResourceManager.GetString("CraftLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vesztettél az arénában!.
        /// </summary>
        public static string Handler_ArenaLose {
            get {
                return ResourceManager.GetString("Handler_ArenaLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyertél az arénában!.
        /// </summary>
        public static string Handler_ArenaWin {
            get {
                return ResourceManager.GetString("Handler_ArenaWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ismeretlen QR!.
        /// </summary>
        public static string Handler_Error {
            get {
                return ResourceManager.GetString("Handler_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR hiba!.
        /// </summary>
        public static string Handler_ErrorTitle {
            get {
                return ResourceManager.GetString("Handler_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem volt elég pénzed a vásárlásra!.
        /// </summary>
        public static string Handler_NotEnoughMoney {
            get {
                return ResourceManager.GetString("Handler_NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezt a csomagot nem neked küldték, vagy már egyszer leolvastad!.
        /// </summary>
        public static string Handler_NotYourStuff {
            get {
                return ResourceManager.GetString("Handler_NotYourStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jutalom.
        /// </summary>
        public static string Handler_QuestRewardTitle {
            get {
                return ResourceManager.GetString("Handler_QuestRewardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikertelen vásárlás!.
        /// </summary>
        public static string Handler_ShopListNotOk {
            get {
                return ResourceManager.GetString("Handler_ShopListNotOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres vásárlás!.
        /// </summary>
        public static string Handler_ShopListOkTitle {
            get {
                return ResourceManager.GetString("Handler_ShopListOkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Handler Page.
        /// </summary>
        public static string Handler_Title {
            get {
                return ResourceManager.GetString("Handler_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A csere oldalon folytathatod a kereskedelmet..
        /// </summary>
        public static string Handler_TradeInProgress {
            get {
                return ResourceManager.GetString("Handler_TradeInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.G.B..
        /// </summary>
        public static string House1 {
            get {
                return ResourceManager.GetString("House1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.Y.R.O.S..
        /// </summary>
        public static string House2 {
            get {
                return ResourceManager.GetString("House2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.A.R.M.A..
        /// </summary>
        public static string House3 {
            get {
                return ResourceManager.GetString("House3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL DARÁLÓK.
        /// </summary>
        public static string House4 {
            get {
                return ResourceManager.GetString("House4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.K.E.A..
        /// </summary>
        public static string House5 {
            get {
                return ResourceManager.GetString("House5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.U.R.M.I.X..
        /// </summary>
        public static string House6 {
            get {
                return ResourceManager.GetString("House6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezt a tárgyat nem használhatod!.
        /// </summary>
        public static string Inventory_CantUse {
            get {
                return ResourceManager.GetString("Inventory_CantUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üres.
        /// </summary>
        public static string Inventory_IsEmpty {
            get {
                return ResourceManager.GetString("Inventory_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eladás.
        /// </summary>
        public static string Inventory_Sell {
            get {
                return ResourceManager.GetString("Inventory_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos, hogy el akarod adni ezt a tárgyat?.
        /// </summary>
        public static string Inventory_SellDialog {
            get {
                return ResourceManager.GetString("Inventory_SellDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hátizsák.
        /// </summary>
        public static string Inventory_Title {
            get {
                return ResourceManager.GetString("Inventory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Használ.
        /// </summary>
        public static string Inventory_Use {
            get {
                return ResourceManager.GetString("Inventory_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Még nem találhatóak bejegyzések!.
        /// </summary>
        public static string Logs_IsEmpty {
            get {
                return ResourceManager.GetString("Logs_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Több betöltése.
        /// </summary>
        public static string Logs_LoadMore {
            get {
                return ResourceManager.GetString("Logs_LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napló.
        /// </summary>
        public static string Logs_Title {
            get {
                return ResourceManager.GetString("Logs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tovább.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos, hogy harcolsz az arénában?.
        /// </summary>
        public static string Profile_ArenaDialog {
            get {
                return ResourceManager.GetString("Profile_ArenaDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Még pihenned kell az előző harc után! Legközelebb ekkor vonulhatsz csatába: .
        /// </summary>
        public static string Profile_CantFightNow {
            get {
                return ResourceManager.GetString("Profile_CantFightNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CritR: {0}%.
        /// </summary>
        public static string Profile_CritR {
            get {
                return ResourceManager.GetString("Profile_CritR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge: {0}%.
        /// </summary>
        public static string Profile_Dodge {
            get {
                return ResourceManager.GetString("Profile_Dodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egy stamina == {0} HP
        ///Egy Def 0.33%-al csökkenti a bekapott sebzést.
        ///Crit Rate és Dodge maximum 60% lehet.
        ///A Crit Rate a kritikus ütés esélye, ami duplán sebez.
        ///A Dodge a kitérésé, akkor nem kapsz be sebzést az adott körben.
        ///1 ATK == random.Next(0,3) sebzés..
        /// </summary>
        public static string Profile_Info {
            get {
                return ResourceManager.GetString("Profile_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs páncél..
        /// </summary>
        public static string Profile_NoArmor {
            get {
                return ResourceManager.GetString("Profile_NoArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs nyaklánc..
        /// </summary>
        public static string Profile_NoNeck {
            get {
                return ResourceManager.GetString("Profile_NoNeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs gyűrű..
        /// </summary>
        public static string Profile_NoRing {
            get {
                return ResourceManager.GetString("Profile_NoRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs fegyver..
        /// </summary>
        public static string Profile_NoWeapon {
            get {
                return ResourceManager.GetString("Profile_NoWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Van már egy folyamatban lévő cseréd!.
        /// </summary>
        public static string Profile_TradeInProgress {
            get {
                return ResourceManager.GetString("Profile_TradeInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR kód leolvasása.
        /// </summary>
        public static string QrScanner_Title {
            get {
                return ResourceManager.GetString("QrScanner_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most nem pontozhatsz!.
        /// </summary>
        public static string Quest_CantScoreError {
            get {
                return ResourceManager.GetString("Quest_CantScoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eredmény.
        /// </summary>
        public static string Quest_Result {
            get {
                return ResourceManager.GetString("Quest_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos, hogy {0} pontot adsz a csapatnak?.
        /// </summary>
        public static string Quest_ResultDialog {
            get {
                return ResourceManager.GetString("Quest_ResultDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontozás.
        /// </summary>
        public static string Quest_Title {
            get {
                return ResourceManager.GetString("Quest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sajnosnemtudom.
        /// </summary>
        public static string QuestPw {
            get {
                return ResourceManager.GetString("QuestPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A csapat értékelje az állomást az alapján, hogy mennyire tetszett nekik:.
        /// </summary>
        public static string Rating_Subtitle {
            get {
                return ResourceManager.GetString("Rating_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Értékelés.
        /// </summary>
        public static string Rating_Title {
            get {
                return ResourceManager.GetString("Rating_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaszt választása:.
        /// </summary>
        public static string Register_Class {
            get {
                return ResourceManager.GetString("Register_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ház választása:.
        /// </summary>
        public static string Register_House {
            get {
                return ResourceManager.GetString("Register_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tulajdonságok: 1 Stamina == 4 HP. +2 ATK alapból..
        /// </summary>
        public static string Register_MageDescription {
            get {
                return ResourceManager.GetString("Register_MageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérlek írj be valamilyen nevet és válassz hőst!.
        /// </summary>
        public static string Register_MissingError {
            get {
                return ResourceManager.GetString("Register_MissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tulajdonságok: 1 Stamina == 5 HP. +2 Dodge és CritR alapból..
        /// </summary>
        public static string Register_RogueDescription {
            get {
                return ResourceManager.GetString("Register_RogueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos, hogy elmented ezt a nevet? A későbbiekben nem módosíthatod!.
        /// </summary>
        public static string Register_SaveDialog {
            get {
                return ResourceManager.GetString("Register_SaveDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csapat neve:.
        /// </summary>
        public static string Register_TeamName {
            get {
                return ResourceManager.GetString("Register_TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csapatnév.
        /// </summary>
        public static string Register_TeamNamePlaceholder {
            get {
                return ResourceManager.GetString("Register_TeamNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil létrehozása.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tulajdonságok: 1 Stamina == 6 HP. +2 DEF alapból..
        /// </summary>
        public static string Register_WarriorDescription {
            get {
                return ResourceManager.GetString("Register_WarriorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aréna.
        /// </summary>
        public static string SelectMode_Arena {
            get {
                return ResourceManager.GetString("SelectMode_Arena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HQ.
        /// </summary>
        public static string SelectMode_Hq {
            get {
                return ResourceManager.GetString("SelectMode_Hq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Állomás.
        /// </summary>
        public static string SelectMode_Quest {
            get {
                return ResourceManager.GetString("SelectMode_Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolt.
        /// </summary>
        public static string SelectMode_Shop {
            get {
                return ResourceManager.GetString("SelectMode_Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérlek válaszd ki, milyen módban indítod az alkalmazást!.
        /// </summary>
        public static string SelectMode_Subtitle {
            get {
                return ResourceManager.GetString("SelectMode_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csapat.
        /// </summary>
        public static string SelectMode_Team {
            get {
                return ResourceManager.GetString("SelectMode_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craft 1 Minimum Pont: .
        /// </summary>
        public static string Settings_Craft1MinPoint {
            get {
                return ResourceManager.GetString("Settings_Craft1MinPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craft 1 kezdete (óra 0-24): .
        /// </summary>
        public static string Settings_Craft1Start {
            get {
                return ResourceManager.GetString("Settings_Craft1Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craft 2 Minimum Pont: .
        /// </summary>
        public static string Settings_Craft2MinPoint {
            get {
                return ResourceManager.GetString("Settings_Craft2MinPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craft 2 kezdete (óra 0-24): .
        /// </summary>
        public static string Settings_Craft2Start {
            get {
                return ResourceManager.GetString("Settings_Craft2Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craft nap: .
        /// </summary>
        public static string Settings_CraftDay {
            get {
                return ResourceManager.GetString("Settings_CraftDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil törlése.
        /// </summary>
        public static string Settings_DeleteProfile {
            get {
                return ResourceManager.GetString("Settings_DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos, hogy törlöd a profilodat?.
        /// </summary>
        public static string Settings_DeleteProfileDialog {
            get {
                return ResourceManager.GetString("Settings_DeleteProfileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isteni üzemmód.
        /// </summary>
        public static string Settings_GodMode {
            get {
                return ResourceManager.GetString("Settings_GodMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Állomás átlag.
        /// </summary>
        public static string Settings_QuestAverage {
            get {
                return ResourceManager.GetString("Settings_QuestAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos, hogy alaphelyzetbe állítod a beállításokat?.
        /// </summary>
        public static string Settings_ResetData {
            get {
                return ResourceManager.GetString("Settings_ResetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A beállítások sikeresen elmentve!.
        /// </summary>
        public static string Settings_SuccessfulSave {
            get {
                return ResourceManager.GetString("Settings_SuccessfulSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Összegzés.
        /// </summary>
        public static string Settings_Sum {
            get {
                return ResourceManager.GetString("Settings_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítások.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alaphelyzet.
        /// </summary>
        public static string Settings_ToDefault {
            get {
                return ResourceManager.GetString("Settings_ToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibás jelszó!.
        /// </summary>
        public static string Settings_WrongPasswor {
            get {
                return ResourceManager.GetString("Settings_WrongPasswor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üres a kosarad, kérlek vegyél valamit!.
        /// </summary>
        public static string Shop_CartIsEmptyError {
            get {
                return ResourceManager.GetString("Shop_CartIsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vásárlás.
        /// </summary>
        public static string Shop_Checkout {
            get {
                return ResourceManager.GetString("Shop_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megveszed az alábbi tárgyakat? Ellenőrizd, hogy van e elég pénzed!.
        /// </summary>
        public static string Shop_CheckoutDialog {
            get {
                return ResourceManager.GetString("Shop_CheckoutDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürítés.
        /// </summary>
        public static string Shop_EmptyCart {
            get {
                return ResourceManager.GetString("Shop_EmptyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 5 tárgyat vehetsz egyszerre!.
        /// </summary>
        public static string Shop_ItemLimit {
            get {
                return ResourceManager.GetString("Shop_ItemLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frissül: .
        /// </summary>
        public static string Shop_RefreshAt {
            get {
                return ResourceManager.GetString("Shop_RefreshAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Összesen: {0}$.
        /// </summary>
        public static string Shop_Sum {
            get {
                return ResourceManager.GetString("Shop_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tesco.
        /// </summary>
        public static string Shop_Title {
            get {
                return ResourceManager.GetString("Shop_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosárba.
        /// </summary>
        public static string Shop_ToCart {
            get {
                return ResourceManager.GetString("Shop_ToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnlyFans.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos ezeket a tárgyakat akarod elcserélni?.
        /// </summary>
        public static string Trade_Dialog {
            get {
                return ResourceManager.GetString("Trade_Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 5 tárgyat adhatsz egyszerre!.
        /// </summary>
        public static string Trade_ItemLimit {
            get {
                return ResourceManager.GetString("Trade_ItemLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs ennyi pénzed!.
        /// </summary>
        public static string Trade_NotEnoughMoney {
            get {
                return ResourceManager.GetString("Trade_NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csere.
        /// </summary>
        public static string Trade_Title {
            get {
                return ResourceManager.GetString("Trade_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha rosszul írtad be a csapat nevét, vagy nem olvassa le a QR-t, akkor buktad a cuccokat!.
        /// </summary>
        public static string Trade_Warning {
            get {
                return ResourceManager.GetString("Trade_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igen.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
